server:
  port: 8080
  servlet:
    context-path: /crud-first
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/crud_spring_yt"
    username: root
    password: 14022002
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
